# Generated by Django 4.2.7 on 2023-12-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_type', to='main_app.task', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_task', to='main_app.typemodel', verbose_name='тип')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_types',
            field=models.ManyToManyField(blank=True, related_name='task', through='main_app.TaskType', to='main_app.typemodel'),
        ),
    ]
