# Generated by Django 4.2.7 on 2023-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_task_task_type_tasktype_task_task_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_types',
            new_name='task_types_old',
        ),
    ]
