# Generated by Django 4.2.7 on 2023-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_task_types_task_task_types_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_types',
            field=models.ManyToManyField(blank=True, related_name='task_set', to='main_app.typemodel'),
        ),
    ]
