# Generated by Django 4.2.7 on 2023-12-14 19:04

from django.db import migrations





def transfer_types(apps, schema_editor):
    Task = apps.get_model('main_app.Task')
    for task in Task.objects.all():
        task.task_types.set(task.task_types_old.all())

def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('main_app.Task')
    for task in Task.objects.all():
        task.task_types_old.set(task.task_types.all())


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_task_task_types'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
