# Generated by Django 4.2.7 on 2023-12-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20231215_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_types_old',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
