# Generated by Django 4.2.7 on 2023-12-19 09:40

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_task_task_types_old_delete_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1150, validators=[main_app.validators.clean_description], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summery',
            field=models.CharField(max_length=100, validators=[main_app.validators.clean_tite], verbose_name='Краткое описание'),
        ),
    ]
