# Generated by Django 4.2.7 on 2023-12-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_task_task_types_old_delete_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(verbose_name='Дата начала')),
                ('date_update', models.DateTimeField(verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1150, verbose_name='Полное описание')),
            ],
        ),
    ]
