# Generated by Django 4.2.7 on 2024-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_projectmodel_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'permissions': [('change_users', 'Изменять список участников'), ('change_projects', 'Редактировать проект'), ('create_projects', 'Создавать проект'), ('delete_projects', 'Удалять проект')]},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('change_tasks', 'Редактировать задачу'), ('create_tasks', 'Создавать задачу'), ('delete_tasks', 'Удалять задачу')]},
        ),
    ]
